name: ${project.name}
main: ${project.groupId}.${project.artifactId}.Entry
version: ${project.version}
author: ghowden/Eluinhost
database: false
depend: [ProtocolLib]
permissions:
  anonymous.chat.bypass:
    default: op